src/Entity/Lecteur.php
<?php


namespace App\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;


/**
 * @ORM\Entity(repositoryClass="App\Repository\LecteurRepository")
 * @ORM\Table(name="lecteur")
 */
class Lecteur implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="SEQUENCE")
     * @ORM\SequenceGenerator(sequenceName="lecteur_idelecteur_seq")
     * @ORM\Column(type="integer",name="idelecteur")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $motdepasse;

    /**
     * @ORM\Column(type="json")
     */
    private $roles;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getRoles()
    {
        $mesroles = $this->roles;
        $mesroles[] = 'ROLE_USER';
        var_dump($mesroles);
        return $mesroles;
    }

    public function getUsername()
    {
        return $this->nom;
    }

    public function getSalt()
    {
        return null;
    }


    public function getPassword()
    {
        return $this->motdepasse;
    }

    /**
     * @param mixed $motdepasse
     */
    public function setMotdepasse($motdepasse): void
    {
        $this->motdepasse = $motdepasse;
    }

    /**
     * @return mixed
     */
    public function getMotdepasse()
    {
        return $this->motdepasse;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

}

templates/apropos.html.twig
<!DOCTYPE html>
<html>

<body>
<h1>{{ titre }}</h1>
En construction...<br>
<a href="{{ path('index') }}">Accueil</a>

</body>

</html>

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}BiblioWeb{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
    </head>
    <body>

    {%  block header %}
        <H1 style="text-align: center"> {{ block('title') }} </H1><HR>
    {% endblock %}

    <div id="content">
        {% block body %}{% endblock %}
    </div>

    {% block footer %}
    <footer>
        Mon site
    </footer>
    {%  endblock %}

    </body>
</html>

templates/index.html.twig
{%  extends 'layout.html.twig' %}

{% block content %}
Bienvenue sur le site BiblioWeb v2<br>
{% endblock %}

templates/layout.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    {% block content %} {% endblock %}

    {%  block menu %}
        <div class="menu">
        <a href="{{ path('index') }}">Accueil</a>
        <a href="{{ path('livre') }}">Liste des livres</a>
        <a href="{{ path('auteur') }}">Liste des auteurs</a>
        <a href="{{ path('lesGenres') }}">Liste des genres</a>
        <a href="{{ path('exemplaire') }}">Liste des exemplaires</a>
        <a href="{{ path('apropos') }}">A propos</a>
        {% if app.user %}
            <a href="{{ path('emprunts') }}">Mes emprunts</a>
            <a href="{{ path('app_logout') }}">Se déconnecter ({{ app.user.username }})</a>
        {%  else %}
            <a href="{{ path('app_login') }}">Se connecter</a>
        {% endif %}
        </div>
    {% endblock %}

{% endblock %}

templates/livre.html.twig
{% extends 'layout.html.twig' %}

{% block title %}
    Details du livre {{ livre.titre }}
{% endblock %}

{% block content %}
    <h1>{{ livre.titre }}</h1>

    <strong>ISBN :</strong> {{ livre.isbn }}
    <br>
    <strong>Auteur : </strong> {{ livre.auteur.prenom ~ " " ~ livre.auteur.nom }}
    <br>
    <strong>Genres : </strong>
    <ul>
        {% for genre in livre.genres %}
            <li><a href="{{ path('leGenre',{id:genre.id}) }}">{{ genre.libelle }}</a></li>
        {% endfor %}
    </ul>

    <br>
    <strong>Exemplaires : </strong>
    <ul>
        {% for exemplaire in lesExemplaires %}
            <li>Exemplaire {{ exemplaire.numero }}
                {% if exemplaire.dateretour is empty %}
                    disponible
                {% else %}
                    emprunté, retour prévu le {{ exemplaire.dateretour|date('d/m/Y') }}
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    <br>
    <div>
        <strong>Résumé :</strong> {{ livre.resume }}
    </div>
    <br>
{% endblock %}

templates/livres.html.twig
{% extends 'layout.html.twig' %}

{% block content %}
<ul>
    {% for livre in livres %}
        <li><a href="{{ path('unlivre',{id:livre.id}) }}">{{ livre.titre }}</a></li>
    {% endfor %}
    </ul>
{%  endblock %}